-- =============================================================
-- CPQ Replacement — Seed Data
-- Generated by generate_seed.py
-- Apply AFTER schema.sql: psql -f schema.sql && psql -f seed_data.sql
-- =============================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- FX RATES (ocean → spot; budget rates need manual backfill)
-- -----------------------------------------------------------------------------

-- Rate direction: units of foreign currency per 1 CAD
-- 1 CAD = rate USD  |  CAD→foreign: × rate  |  foreign→CAD: ÷ rate
-- NOTE: 'ocean' rate type removed — Finance confirmed spot = quote rate.

INSERT INTO fx_rates (currency_code, rate_type, rate_date, rate, notes) VALUES ('', 'spot', '2026-01-01', 1.0, 'Seeded from CPQ v28 extraction; original type was ''ocean''');

-- TODO: backfill 12+ months of 'budget' rates for CapEx CAD derivation.

-- -----------------------------------------------------------------------------
-- PRODUCT CATALOG — TLS Servers
-- -----------------------------------------------------------------------------

-- fusion_id is the external anchor. TEMP- values tracked in pending_fusion_id.

INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('TEMP-promo-server-na', 'Promo Server - NA', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=unmatched');  -- UNMATCHED — TEMP- placeholder; resolve fusion_id before prod go-live
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('TEMP-promo-server-uk', 'Promo Server - UK', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=unmatched');  -- UNMATCHED — TEMP- placeholder; resolve fusion_id before prod go-live
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('1290', 'Pro Series 7.0', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('1288', 'Cluster 5.0 (Dell R440)', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('1289', 'Atomic 5.0 (Dell R650xs)', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=fuzzy');  -- FUZZY MATCH (score=90.0) against 'Atomix 5.0' — verify before prod
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('1254', 'Pro Series 6.0 - M', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('1259', 'Pro Series 6.0 vHost', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('1255', 'Advanced Series 6.0 - M', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('1258', 'Advanced Series 6.0 vHost', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('1263', 'Storage Series 6.0 - M', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('1262', 'Essential Series 6.0 - M', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('943', 'Pro Series 5.0 - M', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('944', 'Pro Series 5.0 vHost', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('945', 'Storage Series 5.0 - M', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('946', 'Storage Series 5.0 vHost', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('957', 'Advanced Series 5.0 - M', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('959', 'Advanced Series 5.0 vHost', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');
INSERT INTO product_catalog (fusion_id, sku_name, sku_nickname, product_type_code, level, vendor, is_active, notes) VALUES ('975', 'Essential Series 5.0 - M', NULL, 'server', 'TLS', NULL, true, 'Seeded from CPQ v28; match_confidence=exact');

-- -----------------------------------------------------------------------------
-- PENDING FUSION IDs — TEMP- placeholders
-- -----------------------------------------------------------------------------

-- These rows must be resolved before production go-live.

INSERT INTO pending_fusion_id (product_id, placeholder_id, sku_name, reason) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'TEMP-promo-server-na', 'Promo Server - NA', 'Product not yet formally released; fusion_id pending assignment');
INSERT INTO pending_fusion_id (product_id, placeholder_id, sku_name, reason) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'TEMP-promo-server-uk', 'Promo Server - UK', 'Product not yet formally released; fusion_id pending assignment');

-- -----------------------------------------------------------------------------
-- SERVER SPECS
-- -----------------------------------------------------------------------------

-- is_promo and min_contract_months set based on CPQ v28 business rules.

INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 16.0, 2.0, false, true, 12, false);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 8.0, 2.0, false, true, 12, false);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 10.0, 2.0, false, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1288'')', 4.0, 2.0, false, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1289'')', 8.0, 1.0, false, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 10.0, 2.0, false, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 10.0, 2.0, true, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 4.0, 1.0, false, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 4.0, 1.0, true, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 12.0, 1.0, false, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 2.0, 1.0, false, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 8.0, 2.0, false, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 8.0, 2.0, true, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 16.0, 1.0, false, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 16.0, 1.0, true, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 4.0, 1.0, false, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 4.0, 1.0, true, false, NULL, true);
INSERT INTO server_specs (product_id, drive_bays, default_cpu_qty, is_vhost, is_promo, min_contract_months, allow_customization) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 4.0, 1.0, false, false, NULL, true);

-- -----------------------------------------------------------------------------
-- PRODUCT PRICING — Server MRC/NRC
-- -----------------------------------------------------------------------------

-- term_months: 0=MTM, 12, 24, 36. Flat rates — NOT multipliers.

INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'USD', 0, NULL, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'USD', 12, 399.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'USD', 24, 349.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'USD', 36, 299.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'CAD', 0, NULL, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'CAD', 12, 529.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'CAD', 24, 459.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'CAD', 36, 399.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'GBP', 0, NULL, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'GBP', 12, 309.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'GBP', 24, 269.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-na'')', 'GBP', 36, 229.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'USD', 0, NULL, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'USD', 12, 389.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'USD', 24, 329.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'USD', 36, 299.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'CAD', 0, NULL, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'CAD', 12, 499.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'CAD', 24, 459.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'CAD', 36, 429.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'GBP', 0, NULL, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'GBP', 12, 269.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'GBP', 24, 249.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''TEMP-promo-server-uk'')', 'GBP', 36, 229.0, 0.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'USD', 0, 1719.0, 1719.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'USD', 12, 1719.0, 1719.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'USD', 24, 1339.0, 1719.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'USD', 36, 1149.0, 1719.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'CAD', 0, 1989.0, 1989.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'CAD', 12, 1989.0, 1989.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'CAD', 24, 1539.0, 1989.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'CAD', 36, 1319.0, 1989.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'GBP', 0, 1429.0, 1429.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'GBP', 12, 1429.0, 1429.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'GBP', 24, 1109.0, 1429.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1290'')', 'GBP', 36, 949.0, 1429.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1288'')', 'USD', 12, 399.0, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1288'')', 'USD', 24, 349.0, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1288'')', 'USD', 36, 299.0, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1288'')', 'CAD', 12, 554.67, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1288'')', 'CAD', 24, 485.33, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1288'')', 'CAD', 36, 415.67, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1289'')', 'USD', 12, 449.0, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1289'')', 'USD', 24, 399.0, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1289'')', 'USD', 36, 349.0, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1289'')', 'CAD', 12, 624.0, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1289'')', 'CAD', 24, 554.67, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1289'')', 'CAD', 36, 485.33, NULL, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'USD', 0, 1079.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'USD', 12, 1079.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'USD', 24, 839.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'USD', 36, 719.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'CAD', 0, 1249.0, 1249.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'CAD', 12, 1249.0, 1249.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'CAD', 24, 969.0, 1249.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'CAD', 36, 829.0, 1249.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'GBP', 0, 899.0, 899.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'GBP', 12, 899.0, 899.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'GBP', 24, 699.0, 899.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1254'')', 'GBP', 36, 599.0, 899.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'USD', 0, 1079.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'USD', 12, 1079.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'USD', 24, 839.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'USD', 36, 719.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'CAD', 0, 1249.0, 1249.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'CAD', 12, 1249.0, 1249.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'CAD', 24, 969.0, 1249.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'CAD', 36, 829.0, 1249.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'GBP', 0, 899.0, 899.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'GBP', 12, 899.0, 899.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'GBP', 24, 699.0, 899.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1259'')', 'GBP', 36, 599.0, 899.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'USD', 0, 839.0, 839.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'USD', 12, 839.0, 839.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'USD', 24, 659.0, 839.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'USD', 36, 559.0, 839.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'CAD', 0, 969.0, 969.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'CAD', 12, 969.0, 969.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'CAD', 24, 759.0, 969.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'CAD', 36, 639.0, 969.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'GBP', 0, 699.0, 699.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'GBP', 12, 699.0, 699.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'GBP', 24, 549.0, 699.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1255'')', 'GBP', 36, 459.0, 699.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'USD', 0, 839.0, 839.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'USD', 12, 839.0, 839.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'USD', 24, 659.0, 839.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'USD', 36, 559.0, 839.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'CAD', 0, 969.0, 969.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'CAD', 12, 969.0, 969.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'CAD', 24, 759.0, 969.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'CAD', 36, 639.0, 969.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'GBP', 0, 699.0, 699.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'GBP', 12, 699.0, 699.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'GBP', 24, 549.0, 699.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1258'')', 'GBP', 36, 459.0, 699.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'USD', 0, 939.0, 939.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'USD', 12, 939.0, 939.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'USD', 24, 729.0, 939.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'USD', 36, 619.0, 939.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'CAD', 0, 1079.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'CAD', 12, 1079.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'CAD', 24, 829.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'CAD', 36, 709.0, 1079.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'GBP', 0, 779.0, 779.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'GBP', 12, 779.0, 779.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'GBP', 24, 599.0, 779.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1263'')', 'GBP', 36, 509.0, 779.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'USD', 0, 309.0, 309.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'USD', 12, 309.0, 309.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'USD', 24, 239.0, 309.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'USD', 36, 209.0, 309.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'CAD', 0, 359.0, 359.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'CAD', 12, 359.0, 359.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'CAD', 24, 279.0, 359.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'CAD', 36, 229.0, 359.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'GBP', 0, 259.0, 259.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'GBP', 12, 259.0, 259.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'GBP', 24, 199.0, 259.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''1262'')', 'GBP', 36, 169.0, 259.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'USD', 0, 849.0, 849.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'USD', 12, 679.0, 849.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'USD', 24, 679.0, 849.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'USD', 36, 679.0, 849.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'CAD', 0, 1147.0, 1147.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'CAD', 12, 919.0, 1147.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'CAD', 24, 919.0, 1147.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'CAD', 36, 919.0, 1147.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'GBP', 0, 637.0, 637.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'GBP', 12, 499.0, 637.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'GBP', 24, 499.0, 637.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''943'')', 'GBP', 36, 499.0, 637.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'USD', 0, 849.0, 849.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'USD', 12, 679.0, 849.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'USD', 24, 679.0, 849.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'USD', 36, 679.0, 849.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'CAD', 0, 1147.0, 1147.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'CAD', 12, 919.0, 1147.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'CAD', 24, 919.0, 1147.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'CAD', 36, 919.0, 1147.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'GBP', 0, 637.0, 637.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'GBP', 12, 499.0, 637.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'GBP', 24, 499.0, 637.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''944'')', 'GBP', 36, 499.0, 637.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'USD', 0, 749.0, 749.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'USD', 12, 599.0, 749.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'USD', 24, 599.0, 749.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'USD', 36, 599.0, 749.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'CAD', 0, 1012.0, 1012.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'CAD', 12, 809.0, 1012.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'CAD', 24, 809.0, 1012.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'CAD', 36, 809.0, 1012.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'GBP', 0, 562.0, 562.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'GBP', 12, 449.0, 562.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'GBP', 24, 449.0, 562.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''945'')', 'GBP', 36, 449.0, 562.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'USD', 0, 749.0, 749.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'USD', 12, 599.0, 749.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'USD', 24, 599.0, 749.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'USD', 36, 599.0, 749.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'CAD', 0, 1012.0, 1012.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'CAD', 12, 809.0, 1012.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'CAD', 24, 809.0, 1012.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'CAD', 36, 809.0, 1012.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'GBP', 0, 562.0, 562.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'GBP', 12, 449.0, 562.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'GBP', 24, 449.0, 562.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''946'')', 'GBP', 36, 449.0, 562.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'USD', 0, 560.0, 560.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'USD', 12, 449.0, 560.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'USD', 24, 449.0, 560.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'USD', 36, 449.0, 560.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'CAD', 0, 756.0, 756.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'CAD', 12, 609.0, 756.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'CAD', 24, 609.0, 756.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'CAD', 36, 609.0, 756.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'GBP', 0, 420.0, 420.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'GBP', 12, 329.0, 420.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'GBP', 24, 329.0, 420.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''957'')', 'GBP', 36, 329.0, 420.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'USD', 0, 560.0, 560.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'USD', 12, 449.0, 560.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'USD', 24, 449.0, 560.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'USD', 36, 449.0, 560.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'CAD', 0, 756.0, 756.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'CAD', 12, 609.0, 756.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'CAD', 24, 609.0, 756.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'CAD', 36, 609.0, 756.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'GBP', 0, 420.0, 420.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'GBP', 12, 329.0, 420.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'GBP', 24, 329.0, 420.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''959'')', 'GBP', 36, 329.0, 420.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'USD', 0, 389.0, 389.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'USD', 12, 319.0, 389.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'USD', 24, 319.0, 389.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'USD', 36, 319.0, 389.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'CAD', 0, 529.0, 529.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'CAD', 12, 429.0, 529.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'CAD', 24, 429.0, 529.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'CAD', 36, 429.0, 529.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'GBP', 0, 309.0, 309.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'GBP', 12, 249.0, 309.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'GBP', 24, 249.0, 309.0, 'flat');
INSERT INTO product_pricing (product_id, currency_code, term_months, mrc, nrc, pricing_model) VALUES ('(SELECT id FROM product_catalog WHERE fusion_id = ''975'')', 'GBP', 36, 249.0, 309.0, 'flat');

-- -----------------------------------------------------------------------------
-- SERVER DC AVAILABILITY
-- -----------------------------------------------------------------------------

INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');
INSERT INTO server_dc_availability (server_product_id, dc_code) VALUES ('(SELECT id FROM product_catalog WHERE sku_name = '''' AND level = ''TLS'')', '');

-- -----------------------------------------------------------------------------
-- DC COST DRIVERS
-- -----------------------------------------------------------------------------

INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);
INSERT INTO dc_cost_drivers (dc_code, cost_category, amount, currency_code, notes) VALUES ('', NULL, NULL, 'USD', NULL);

-- -----------------------------------------------------------------------------
-- OVERHEAD CONSTANTS — update from 09_overhead_constants.json
-- -----------------------------------------------------------------------------

-- Schema already seeds defaults. This block updates with CPQ v28 values.

INSERT INTO overhead_constants (key, value, description) VALUES ('sga_pct_of_revenue', 0.08199743735763099, 'From CPQ v28 extraction') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO overhead_constants (key, value, description) VALUES ('annual_cost_inflation_rate', 0.03, 'From CPQ v28 extraction') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO overhead_constants (key, value, description) VALUES ('software_markup_over_cost', 0.15, 'From CPQ v28 extraction') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO overhead_constants (key, value, description) VALUES ('ebit_thresholds', '{''poor_below'': -0.1, ''moderate'': 0.35, ''good'': 0.375, ''strong'': 0.4}', 'From CPQ v28 extraction') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO overhead_constants (key, value, description) VALUES ('capital_intensity_threshold', 0.5, 'From CPQ v28 extraction') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
INSERT INTO overhead_constants (key, value, description) VALUES ('notes', '{''sga'': ''SG&A as % of Revenue - sourced from Model-Hosting!D8 and Model-Drivers row 10 (8.2%)'', ''inflation'': ''Annual cost inflation applied to per-server/per-kW cost drivers - sourced from Model-Hosting!D9'', ''software_markup'': ''Software costs in Products-Hosting col AC are wholesale/actual; col AD is adjusted. Model-Hosting uses 15% markup over actual cost to arrive at revenue (Model-Hosting!C72)'', ''ebit_thresholds'': "Approval gate thresholds. Deals below ''poor'' require Finance; ''moderate'' requires Director; ''good'' is standard approval; ''strong'' auto-approve", ''capital_intensity'': ''CI = CapEx / TCV. Target CI threshold is 0.50 (50%)''}', 'From CPQ v28 extraction') ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

COMMIT;

-- Run validation.md queries to confirm correctness.